<?php

return [
    "USER_TYPES" => [
        "en" => [
            '' => "--- choose a user type ---",
            'admin' => 'Admin',
            'user' => 'User',
            'doctor' => 'Doctor',
            'admin_place_of_consultation' => 'Place of consultations coordinator',
            'admin_establishment' => 'Establishment coordinator',
            'admin_service' => 'Service coordinator'
        ],
        "fr" => [
            '' => "--- choisir un type d'utilisateur ---",
            'admin' => 'Administrateur',
            'user' => 'Utilisateur',
            'doctor' => 'Médecin',
            'admin_place_of_consultation' => 'Coordinateur du lieu de consultation',
            'admin_establishment' => "Coordinateur de l'établissement",
            'admin_service' => 'Coordinateur de service'
        ],
        "ar" => [
            '' => "--- اختر نوع مستخدم ---",
            'admin' => 'مدير',
            'user' => 'مستخدم',
            'doctor' => 'طبيب',
            'admin_place_of_consultation' => 'منسق مكان الاستشارة',
            'admin_establishment' => "منسق المؤسسة",
            'admin_service' => 'منسق الخدمة'
        ]
    ],

    "SPECIALTY_OPTIONS" => [
        "en" => [
            ""=>"--- Choose a Specialty ---",
            "allergology"=>"Allergology",
            "anesthesiology"=>"Anesthesiology",
            "andrology"=>"Andrology",
            "cardiology"=>"Cardiology",
            "cardiac_surgery"=>"Cardiac Surgery",
            "aesthetic_plastic_reconstructive_surgery"=>"Aesthetic, Plastic, and Reconstructive Surgery",
            "general_surgery"=>"General Surgery",
            "maxillofacial_surgery"=>"Maxillofacial Surgery",
            "pediatric_surgery"=>"Pediatric Surgery",
            "thoracic_surgery"=> "Thoracic Surgery",
            "vascular_surgery"=>"Vascular Surgery",
            "neurosurgery"=>"Neurosurgery",
            "dermatology"=>"Dermatology",
            "endocrinology"=>"Endocrinology",
            "gastroenterology"=>"Gastroenterology",
            "geriatrics"=>"Geriatrics",
            "obstetrics_gynecology"=>"Obstetrics and Gynecology",
            "hematology"=>"Hematology",
            "hepatology"=>"Hepatology",
            "infectious_diseases"=>"Infectious Diseases",
            "occupational_medicine"=>"Occupational Medicine",
            "nuclear_medicine"=>"Nuclear Medicine",
            "neonatology"=>"Neonatology",
            "nephrology"=>"Nephrology",
            "neurology"=>"Neurology",
            "dentistry"=>"Dentistry",
            "oncology"=>"Oncology",
            "ophthalmology"=>"Ophthalmology",
            "orthopedics"=>"Orthopedics",
            "pediatrics"=>"Pediatrics",
            "pulmonology"=>"Pulmonology",
            "radiology"=>"Radiology",
            "radiotherapy"=>"Radiotherapy",
            "rheumatology"=>"Rheumatology",
            "urology"=>"Urology"
        ],
        "fr" => [
            ""=>"--- Choisissez une spécialité ---",
            "allergology"=>"Allergologie",
            "anesthesiology"=>"Anesthésiologie",
            "andrology"=>"Andrologie",
            "cardiology"=>"Cardiologie",
            "cardiac_surgery"=>"Chirurgie cardiaque",
            "aesthetic_plastic_reconstructive_surgery"=>"Chirurgie plastique esthétique et reconstructrice",
            "general_surgery"=>"Chirurgie générale",
            "maxillofacial_surgery"=>"Chirurgie maxillo-faciale",
            "pediatric_surgery"=>"Chirurgie pédiatrique",
            "thoracic_surgery"=> "Chirurgie thoracique",
            "vascular_surgery"=>"Chirurgie vasculaire",
            "neurosurgery"=>"Neurochirurgie",
            "dermatology"=>"Dermatologie",
            "endocrinology"=>"Endocrinologie",
            "gastroenterology"=>"Gastro-entérologie",
            "geriatrics"=>"Gériatrie",
            "obstetrics_gynecology"=>"Obstétrique et gynécologie",
            "hematology"=>"Hématologie",
            "hepatology"=>"Hépatologie",
            "infectious_diseases"=>"Maladies infectieuses",
            "occupational_medicine"=>"Médecine du travail",
            "nuclear_medicine"=>"Médecine nucléaire",
            "neonatology"=>"Néonatologie",
            "nephrology"=>"Néphrologie",
            "neurology"=>"Neurologie",
            "dentistry"=>"Dentisterie",
            "oncology"=>"Oncologie",
            "ophthalmology"=>"Ophtalmologie",
            "orthopedics"=>"Orthopédie",
            "pediatrics"=>"Pédiatrie",
            "pulmonology"=>"Pneumologie",
            "radiology"=>"Radiologie",
            "radiotherapy"=>"Radiothérapie",
            "rheumatology"=>"Rhumatologie",
            "urology"=>"Urologie"
        ],
        "ar" => [
            ""=>"--- اختر تخصصًا ---",
            "allergology"=>"الحساسية والمناعة",
            "anesthesiology"=>"علم التخدير",
            "andrology"=>"علم الذكورة",
            "cardiology"=>"طب القلب",
            "cardiac_surgery"=>"جراحة القلب",
            "aesthetic_plastic_reconstructive_surgery"=>"جراحة التجميل والترميمية",
            "general_surgery"=>"جراحة عامة",
            "maxillofacial_surgery"=>"جراحة الفك والوجه",
            "pediatric_surgery"=>"جراحة الأطفال",
            "thoracic_surgery"=> "جراحة الصدر",
            "vascular_surgery"=>"جراحة الأوعية الدموية",
            "neurosurgery"=>"جراحة الأعصاب",
            "dermatology"=>"طب الأمراض الجلدية",
            "endocrinology"=>"علم الغدد الصماء",
            "gastroenterology"=>"الجهاز الهضمي",
            "geriatrics"=>"طب المسنين",
            "obstetrics_gynecology"=>"طب النساء والتوليد",
            "hematology"=>"علم الدم",
            "hepatology"=>"علم الكبد",
            "infectious_diseases"=>"الأمراض المعدية",
            "occupational_medicine"=>"الطب الوظيفي",
            "nuclear_medicine"=>"الطب النووي",
            "neonatology"=>"طب حديثي الولادة",
            "nephrology"=>"علم الكلى",
            "neurology"=>"طب الأعصاب",
            "dentistry"=>"طب الأسنان",
            "oncology"=>"علم الأورام",
            "ophthalmology"=>"طب العيون",
            "orthopedics"=>"طب العظام",
            "pediatrics"=>"طب الأطفال",
            "pulmonology"=>"أمراض الرئة",
            "radiology"=>"الأشعة التشخيصية",
            "radiotherapy"=>"العلاج الإشعاعي",
            "rheumatology"=>"أمراض المفاصل",
            "urology"=>"المسالك البولية"
        ]
    ],

    "DAIRAS" => [
        "fr" => [
            "" => "--- Choisir Une Daïra ---",
            "tlemcen" => "Tlemcen",
            "mansourah" => "Mansourah",
            "chetouane" => "Chetouane",
            "sabra" => "Sabra",
            "remchi" => "Remchi",
            "hennaya" => "Hennaya",
            "honaine" => "Honaine",
            "maghnia" => "Maghnia",
            "beni_boussaid" => "Beni Boussaid",
            "bab_el_assa" => "Bab El Assa",
            "marseet_ben_mhidi" => "Marsset Ben M'hidi",
            "sebdou" => "Sebdou",
            "sidi_djillali" => "Sidi Djillali",
            "beni_snouss" => "Beni Snouss",
            "ouled_mimoun" => "Ouled Mimoun",
            "bensekrane" => "Bensekrane",
            "ain_tellout" => "Ain Tellout",
            "ghazaouet" => "Ghazaouet",
            "nedroma" => "Nedroma",
            "fellaoucene" => "Fellaoucene"
        ],
        "en" => [
            "" => "--- Choose a Daïra ---",
            "tlemcen" => "Tlemcen",
            "mansourah" => "Mansourah",
            "chetouane" => "Chetouane",
            "sabra" => "Sabra",
            "remchi" => "Remchi",
            "hennaya" => "Hennaya",
            "honaine" => "Honaine",
            "maghnia" => "Maghnia",
            "beni_boussaid" => "Beni Boussaid",
            "bab_el_assa" => "Bab El Assa",
            "marseet_ben_mhidi" => "Marsset Ben M'hidi",
            "sebdou" => "Sebdou",
            "sidi_djillali" => "Sidi Djillali",
            "beni_snouss" => "Beni Snouss",
            "ouled_mimoun" => "Ouled Mimoun",
            "bensekrane" => "Bensekrane",
            "ain_tellout" => "Ain Tellout",
            "ghazaouet" => "Ghazaouet",
            "nedroma" => "Nedroma",
            "fellaoucene" => "Fellaoucene"
        ],
        "ar" => [
            "" => "--- اختر دائرة ---",
            "tlemcen" => "تلمسان",
            "mansourah" => "المنصورة",
            "chetouane" => "شتوان",
            "sabra" => "صبرة",
            "remchi" => "الرمشي",
            "hennaya" => "حناية",
            "honaine" => "حنين",
            "maghnia" => "مغنية",
            "beni_boussaid" => "بني بوسعيد",
            "bab_el_assa" => "باب العسة",
            "marseet_ben_mhidi" => "مرسى بن مهيدي",
            "sebdou" => "سبدو",
            "sidi_djillali" => "سيدي جيلالي",
            "beni_snouss" => "بني سنوس",
            "ouled_mimoun" => "أولاد ميمون",
            "bensekrane" => "بني صقران",
            "ain_tellout" => "عين تالوت",
            "ghazaouet" => "غزوات",
            "nedroma" => "ندرومة",
            "fellaoucene" => "فلاوسن"
        ]
    ]
,
    "YEARS" => [
        "" => "--- Choisir Une Année ---",
        "2024" => "2024",
        "2025" => "2025",
        "2026" => "2026",
        "2027" => "2027",
        "2028" => "2028",
        "2029" => "2029",
        "2030" => "2030",
        "2031" => "2031",
        "2032" => "2032",
        "2033" => "2033",
        "2034" => "2034",
        "2035" => "2035",
        "2036" => "2036",
        "2037" => "2037",
        "2038" => "2038",
        "2039" => "2039",
        "2040" => "2040",
        "2041" => "2041",
        "2042" => "2042",
        "2043" => "2043",
        "2044" => "2044",
        "2045" => "2045",
        "2046" => "2046",
        "2047" => "2047",
        "2048" => "2048",
        "2049" => "2049",
        "2050" => "2050"
    ],

    "MONTHS_OPTIONS" => [
        "fr" => [
            "" => "--- Choisir Un Mois ---",
            '1' => 'Janvier',
            '2' => 'Février',
            '3' => 'Mars',
            '4' => 'Avril',
            '5' => 'Mai',
            '6' => 'Juin',
            '7' => 'Juillet',
            '8' => 'Août',
            '9' => 'Septembre',
            '10' => 'Octobre',
            '11' => 'Novembre',
            '12' => 'Décembre',
        ],
        "en" => [
            "" => "--- Choose a Month ---",
            '1' => 'January',
            '2' => 'February',
            '3' => 'March',
            '4' => 'April',
            '5' => 'May',
            '6' => 'June',
            '7' => 'July',
            '8' => 'August',
            '9' => 'September',
            '10' => 'October',
            '11' => 'November',
            '12' => 'December',
        ],
        "ar" => [
            "" => "--- اختر شهرًا ---",
            '1' => 'يناير',
            '2' => 'فبراير',
            '3' => 'مارس',
            '4' => 'أبريل',
            '5' => 'مايو',
            '6' => 'يونيو',
            '7' => 'يوليو',
            '8' => 'أغسطس',
            '9' => 'سبتمبر',
            '10' => 'أكتوبر',
            '11' => 'نوفمبر',
            '12' => 'ديسمبر',
        ],
    ],
    'PLANNING_STATE' => [
        "fr" => [
            "" => "--- spécifier l'état ---",
            'published' => 'Publié',
            'not_published' => 'Non publié',
        ],
        "en" => [
            "" => "--- Specify State ---",
            'published' => 'Published',
            'not_published' => 'Not Published',
        ],
        "ar" => [
            "" => "--- حدد الحالة ---",
            'published' => 'تم النشر',
            'not_published' => 'غير منشور',
        ],
    ],
    'RENDEZ_VOUS_TYPE' => [
        "fr" => [
            "" => "--- Spécifiez le type ---",
            'normal' => 'Rendez-vous',
            'control' => 'Contrôle',
        ],
        "en" => [
            "" => "--- Specify Type ---",
            'normal' => 'Appointment',
            'control' => 'Checkup',
        ],
        "ar" => [
            "" => "--- حدد النوع ---",
            'normal' => 'موعد',
            'control' => 'فحص'
        ],
    ],

    'PLANNING_DAY_STATE' => [
        "fr" => [
            "" => "--- État de la journée de planification ---",
            'complete' => 'Complet',
            'incomplete' => 'Incomplet',
        ],
        "ar" => [
            "" => "--- حالة يوم التخطيط ---",
            'complete' => 'مكتمل',
            'incomplete' => 'غير مكتمل',
        ],
        "en" => [
            "" => "--- Planning Day State ---",
            'complete' => 'Complete',
            'incomplete' => 'Incomplete',
        ],
    ],
    "MONTHS" => [
        "fr" => ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
        "ar" => ['يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو', 'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر'],
        "en" => ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
    ]


];
