<?php

return [
    "SPECIALTY_OPTIONS" => [
        ["", "--- Choisir Une Spécialité ---"],
        ["allergologie", "allergologie"],
        ["anesthésiologie", "anesthésiologie"],
        ["andrologie", "andrologie"],
        ["cardiologie", "cardiologie"],
        ["chirurgie cardiaque", "chirurgie cardiaque"],
        ["chirurgie esthétique, plastique et reconstructive", "chirurgie esthétique, plastique et reconstructive"],
        ["chirurgie générale", "chirurgie générale"],
        ["chirurgie maxillo-faciale", "chirurgie maxillo-faciale"],
        ["chirurgie pédiatrique", "chirurgie pédiatrique"],
        ["chirurgie thoracique", "chirurgie thoracique"],
        ["chirurgie vasculaire", "chirurgie vasculaire"],
        ["neurochirurgie", "neurochirurgie"],
        ["dermatologie", "dermatologie"],
        ["endocrinologie", "endocrinologie"],
        ["gastro-entérologie", "gastro-entérologie"],
        ["gériatrie", "gériatrie"],
        ["gynécologie obstétrique", "gynécologie obstétrique"],
        ["hématologie", "hématologie"],
        ["hépatologie", "hépatologie"],
        ["infectiologie", "infectiologie"],
        ["médecine du travail", "médecine du travail"],
        ["médecine nucléaire", "médecine nucléaire"],
        ["néonatalogie", "néonatalogie"],
        ["néphrologie", "néphrologie"],
        ["neurologie", "neurologie"],
        ["odontologie", "odontologie"],
        ["oncologie", "oncologie"],
        ["ophtalmologie", "ophtalmologie"],
        ["orthopédie", "orthopédie"],
        ["pédiatrie", "pédiatrie"],
        ["pneumologie", "pneumologie"],
        ["radiologie", "radiologie"],
        ["radiothérapie", "radiothérapie"],
        ["rhumatologie", "rhumatologie"],
        ["urologie", "urologie"]
    ],

    "DAIRAS" => [
        ["", "--- Choisir Une Daïra ---"],
        ["tlemcen", "Tlemcen"],
        ["mansourah", "Mansourah"],
        ["chetouane", "Chetouane"],
        ["sabra", "Sabra"],
        ["remchi", "Remchi"],
        ["hennaya", "Hennaya"],
        ["honaine", "Honaine"],
        ["maghnia", "Maghnia"],
        ["beni_boussaid", "Beni Boussaid"],
        ["bab_el_assa", "Bab El Assa"],
        ["marseet_ben_mhidi", "Marsset Ben M'hidi"],
        ["sebdou", "Sebdou"],
        ["sidi_djillali", "Sidi Djillali"],
        ["beni_snouss", "Beni Snouss"],
        ["ouled_mimoun", "Ouled Mimoun"],
        ["bensekrane", "Bensekrane"],
        ["ain_tellout", "Ain Tellout"],
        ["ghazaouet", "Ghazaouet"],
        ["nedroma", "Nedroma"],
        ["fellaoucene", "Fellaoucene"]
    ],
    "YEARS" => [
        ["", "--- Choisir Une Année ---"],
        ['2023','2023'],
        ['2024','2024'],
        ['2025','2025'],
        ['2026','2026'],
        ['2027','2027'],
        ['2028','2028'],
        ['2029','2029'],
        ['2030','2030'],
        ['2031','2031'],
        ['2032','2032'],
        ['2033','2033'],
        ['2034','2034'],
        ['2035','2035'],
        ['2036','2036'],
        ['2037','2037'],
        ['2038','2038'],
        ['2039','2039'],
        ['2040','2040'],
        ['2041','2041'],
        ['2042','2042'],
        ['2043','2043'],
        ['2044','2044'],
        ['2045','2045'],
        ['2046','2046'],
        ['2047','2047'],
        ['2048','2048'],
        ['2049','2049'],
        ['2050','2050'],
    ],
    "MONTHS_OPTIONS" => [
        ["", "--- Choisir Un Mois ---"],
        ['1', 'Janvier'],
        ['2', 'Février'],
        ['3', 'Mars'],
        ['4', 'Avril'],
        ['5', 'Mai'],
        ['6', 'Juin'],
        ['7', 'Juillet'],
        ['8', 'Août'],
        ['9', 'Septembre'],
        ['10', 'Octobre'],
        ['11', 'Novembre'],
        ['12', 'Décembre'],
    ],
    "MONTHS" => [
        'Janvier', 'Février', 'Mars', 'Avril', 'Mai',
         'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre','Novembre', 'Décembre'],
    'PLANNING_STATE'=>[
        ["", "--- spécifier l'état ---"],
        ['publié','publié'],
        ['non publié','non publié']
        ]
];
